name: test_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  sliding_up_panel: ^2.0.0+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_compass: ^0.8.0
  flutter_map_location_marker: ^9.1.1
  http: ^1.2.2
  provider: ^6.0.0 # Add the provider package here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/purple_jeepney.png
    - assets/images/yellow_jeepney.png
    - assets/images/green_jeepney.png
    - assets/images/brown_jeepney.png
